import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SiteNavigation } from "@/components/SiteNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} text-white bg-slate-800`}
      >
        <SiteNavigation />
        <Providers>{children}</Providers>
        <Analytics />
      </body>
    </html>
  );
}
